I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 348, in script
    $ feedback_pool = voir_dire_feedback[current_category][feedback_tier]
  File "game/script.rpy", line 348, in <module>
    $ feedback_pool = voir_dire_feedback[current_category][feedback_tier]
NameError: name 'feedback_tier' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 348, in script
    $ feedback_pool = voir_dire_feedback[current_category][feedback_tier]
  File "C:\Users\navya\Downloads\renpy-8.3.3-sdk\renpy\ast.py", line 821, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\navya\Downloads\renpy-8.3.3-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 348, in <module>
    $ feedback_pool = voir_dire_feedback[current_category][feedback_tier]
NameError: name 'feedback_tier' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.3.24111502
Court Room Scene 1.0
Mon Mar 24 11:03:51 2025
